import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { ProviderTheme } from "@/components/themeprovider";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { db } from "@/lib/mogo";
import { Cabin } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import QueryProvider from "@/lib/provider";

const cabin = Cabin({
  subsets: ["latin"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Shop and Malls",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await db();
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased ${cabin.className}`}
        >
          {/* <ProviderTheme> */}
          <QueryProvider>
            <Navbar />
            <div className="container min-h-[80vh]">{children}</div>
            <Footer />
          </QueryProvider>
          {/* </ProviderTheme> */}
        </body>
      </html>
    </SessionProvider>
  );
}
